### ISSUE TITLE
How antox get connected?

### ISSUE THREAD

**Issue by OleksandrLos** [Astonex/Antox#687]
I'm playing around with antox and noticed that when I restricted access to NodeFile from online and from res/raw in logcat I got such messages:
"couldn't reach Nodefile URL" and 
"readJsonFromFile error: org.json.JSONException: End of input at character 0 of" (emty file)
but Antox get connected anyway. How?

**Comment by subliun** [comment]
The nodefile from online is saved to another file which it loads from if the Nodefile url can't be reached. If it's not that then you've probably connected to nodes stored in your Tox data file. Otherwise you might be automatically connected to someone else on the same LAN

There are lots of ways for Antox to connect :)

**Comment by OleksandrLos** [comment]
Thanks for your reply!
It's seems like a virus ))
